### ISSUE TITLE
Making convenient to add new ingredients

### ISSUE THREAD

**Issue by JPengel** [JPengel/teamproject-group-2-four-continents#2]
The idea is to change methods/classes to make the experience of adding new ingredients to the game more convenient. At the moment any developer that would like to add a new food to the game would need to add 3 different images, add sounds, change manually the ToppingType (enum) class, the Mode class (in several places), and the GameOver class(addToppings()). Besides that they would also need to change the hide/show content methods in every class. The main idea is to have the experience of adding new ingredients reduced to adding the images/sounds to the folder and adding 1 line of code to the ToppingType class. To do so, I would need to change various things, such as adding a method at the ToppingType class that returns the enum position of the last ingredient added to the game(not counting hazards). In the Mode class, I would need to have the methods, MouseDrag(), generateObject(), and checkForEffects() modified, working based on the enum method inside ToppingType instead of having multiple if statements checking for matches. The same approach would need to be used to change the hide/show content in all classes. In addition to these changes, the game over UI would also need to be modified, since it was made to display 3 ingredients only (possible change : instead of showing the count of each ingredient that was sliced, I could display the user's high score). 
PS : There is still a problem with the item sliced counters in the Mode class that I still don't know how to make more convenient, after figuring it out I will be able to understand how to remodel the logic inside the addToppings()method that belongs to the GameOver class since it depends on the ingredient counters in Mode.

**Comment by onzfonz** [comment]
Do this one but try to take it one step further and have all of the ingredients be loaded from a file or set of files instead, that way someone could add new ingredients without even touching the code.
